name: GitHub Pages

on:
  push:
    branches:
      - dev
    paths:
      - "public/**"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./public
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public